---
provider: github
changes:
    major:
        - break
    minor:
        - feat
        - improve
    patch:
        - fix
        - chore
        - refactor
        - test
        - docs
        - build
        - types
        - style
        - workflow
        - perf
        - revert
output:
    filePath: CHANGELOG.md
    exclude:
        author: ['dependabot-preview[bot]']
        type: ['build']
        scope: ['deps', 'deps-dev']
        subject: ['merge']
plugins:
    attention:
        title: Important Changes
        templates:
            added: 'Added %name% with %val%'
            changed: 'Changed %name% from %pval% to %val%'
            bumped: 'Bumped %name% from %pver% to %ver%'
            downgraded: 'Downgraded %name% from %pver% to %ver%'
            removed: 'Removed %name%, with %pval%'
            unchanged: '%name% left unchanged, with %val%'
        sections:
            license: License
            engine: Engine
            dependencies: Dependencies
            devDependencies: DevDependencies
            peerDependencies: PeerDependencies
            optionalDependencies: OptionalDependencies,
    # List of available markers
    markers:
        # !important - place a commit title to special section on top of changelog
        important: Important Internal Changes
        # !deprecated - place a commit title to special section with deprecated properties
        deprecated: DEPRECATIONS
        # !break - indicates major changes breaking backward compatibility
        break: BREAKING CHANGES
        # !hide - hide a commit
        hide: Hidden commits
        # !group(NAME) - creates a group of commits with the <NAME>
        group: Grouped commit
    # list of major scopes
    scopes:
        only: false
        list:
            core: Core
            api: API
            ssr: Server Side Rendering
            fc: Functional Components
            dts: TypeScript Declaration Improvements
    sections:
        - Features: [feat]
        - Improvements: [improve]
        - Bug Fixes: [fix]
        - Internal changes: [types, workflow, build, test, chore, docs]
        - Performance Improvements: [perf]
        - Code Refactoring: [refactor]
        - Reverts: [revert]
