---
plugins: [flag, scope, section]
types:
    - feat
    - fix
    - chore
    - refactor
    - test
    - docs
    - ci
    - types
    - style
    - workflow
    - perf
    - break
    - revert
flags:
    # !important <comment> - place <comment> to special section on top of changelog
    - important
    # !hide - hide commit
    - hide
    # !group <name> - creates a group of commits with the <name>
    - group
    # !deprecated <comment> - place <comment> to special section with deprecated propertyes
    - deprecated
    # !break <comment> - indicates major changes breaking backward compatibility
    - break
# list of major scopes
scopes:
    - common
    - core
    - theme
    - api
    - package
sections:
    - Features:
        - feat
    - Bugfixes:
        - fix
    - Internal сhanges:
        - types
        - workflow
        - ci
        - test
        - chore
        - docs
    - Breaking сhanges:
        - break
    - Performance:
        - perf
    - Refactoring:
        - refactor
    - Reverts:
        - revert
