---
plugins: [sign, scope, section]
types:
    - feat
    - fix
    - chore
    - refactor
    - test
    - docs
    - ci
    - build
    - types
    - style
    - workflow
    - perf
    - break
    - revert
# List of avaliable signs
signs:
    # !important - place a commit title to special section on top of changelog
    - important
    # !hide - hide a commit
    - hide
    # !group(NAME) - creates a group of commits with the <NAME>
    - group
    # !deprecated- place a commit title to special section with deprecated propertyes
    - deprecated
    # !break - indicates major changes breaking backward compatibility
    - break
# list of major scopes
scopes:
    - common
    - core
    - theme
    - api
    - package
sections:
    - Features:
        - feat
    - Bugfixes:
        - fix
    - Internal сhanges:
        - types
        - workflow
        - ci
        - build
        - test
        - chore
        - docs
    - Breaking сhanges:
        - break
    - Performance:
        - perf
    - Refactoring:
        - refactor
    - Reverts:
        - revert
